### PR TITLE
NSLC cleanup

### PR DESCRIPTION
**Pull request by sboltz**
This PR standardizes and cleans up the way that NSLC information is handled, particularly if it contains numeric values (particularly location codes). This is necessary because pandas can do strange things to dtypes that result in unexpected behavior.

It should have the following behavior:

- If dtypes for any of the NSLC columns are floats, then they will be converted to 2-digit zero-padded strings (`1.0` becomes `"01"`)
- If dtypes for any of the NSLC columns are ints, then they will be converted to 2-digit zero-padded strings (`1` becomes `"01"`)
- If dtypes for any of the NSLC columns are strs, then they will be left alone (`"1"` becomes  `"1"` and `"01"` becomes  `"01"`)
- If dtypes for any of the NSLC columns are strs, but they happen to contain decimals, a TypeError will raise because this will cause confusion elsewhere (`"1.0"` will not be allowed)

This behavior should coerce things to follow the seed convention, but it will also allow for special cases where the NSLC are purely numeric.

### CODE REVIEW

**Comment by d-chambers** [comment]
This looks well thought out. I especially like how you are using a custom dtype for NSLC codes to replace a multitude of ad-hacks. 

It looks like it still needs a changelog entry. Apart from that, is there anything left to do?

**Comment by d-chambers** [comment]
I do have one question about station codes. These are typically 3 characters, probably for historical reasons. I think the seed spec just requires they are between 1 and 5 chars though. It might be nice if station 1 became station "001" rather than "01" but I suppose it isn't that important. What do you think?

**Comment by sboltz** [comment]
> I do have one question about station codes. These are typically 3 characters, probably for historical reasons. I think the seed spec just requires they are between 1 and 5 chars though. It might be nice if station 1 became station "001" rather than "01" but I suppose it isn't that important. What do you think?

That is an interesting point. For simplicity, I would say that if the user wants to name their station "001", they should use the string convention that we have outlined. But that is largely out of laziness and because it's difficult to figure out what the appropriate thing to do there really is. For instance, for us we would almost certainly want station 1 to become station "1". The reason for having it be "01" is because all of the NSLC components are now using the same data type, and in particular I wanted to make sure it handles location codes properly.

**Comment by d-chambers** [comment]
Looks good

**Pull request merged**
