### PR TITLE
Allow minimal updates

### PR DESCRIPTION
**Pull request by calum-chamberlain**
When using `EventBank.put_events` you have the option to either update the index (default) or not. If the index is not updated the new events do not appear in the index.  This is possibly expected, but seems to be an incomplete way of putting events.  This PR is *an idea* for adding new events to the index without iterating the whole database. It simply adds a `paths` argument to `update_index` and uses these paths if given, but defaults to updating the entire index. `paths` is passed from `put_events` when `update_index=False`.

Motivation:
---
I have a large database spanning 30 years and >500,000 events, which has a structure like `{year}/{month}/{eventid}` with at least five files in each event directory (waveform, processed waveform, quakeml, json and links to other events). Iterating through the entire database is slow, even when using a local drive, and seems unnecessary when I know I haven't updated any other files other than the newly added events.

Aside
---
Just doing something silly here (instantiating a bank on my Desktop) results in `update_index` taking a while because it scans all the directories and files on my Desktop rather than only those matching the format-spec of the bank.  This is obviously a stupid example and user error, but it does highlight a possible issue - any additional files added to the bank path will be iterated. Not sure how to get around that other than making it obvious to a user that they should keep their bank separate from other things.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
I'm not sure if this would cause an issue with the update-time of the dataframe?

**Comment by sboltz** [comment]
I’ll take a look at this pull request more closely in a bit, but I did want to comment. 

The reason for having the ‘update_index=False’ option was actually for a particular use-case of mine where I was working with a 10,000 event catalog processing each event in parallel. I wanted to be able to write the events to back to disk as I went and be able to just update the index once at the end, rather than having each process try and do it and the potential pandemonium that would ensue.

**Comment by calum-chamberlain** [comment]
Ah, that would cause problems! This implementation would still cause issues for that use-case and perhaps isn't desirable. This PR also is not complete (it has no tests for starters), so don't give it a full review!

Thanks!

**Comment by d-chambers** [comment]
@calum-chamberlain I like the simplicity of this. I imagine it would also help immensely if you are still  using a bank on a network-mounted drive.  

I think it may be viable, but we do need to think carefully about how to update the timestamp stored in the index file. We also would want to preserve the option to not update the index in order to meet @sboltz's needs.

Here is the problem as I see it:
Imagine you put events which triggers the `update_index` function using the `paths` parameter. It will then parse *only* the paths provided and set the `last_updated` timestamp to the time `put_events` was called. However, if another process adds files to the bank directory these will not be accounted for when the index is updated, and presumably, their mtime's will now be smaller than `last_updated` so they will never get indexed.

Now, it is hacky but we could write the new event files, set their mtimes back to a second or so before before the bank's `last_updated` timestamp, then skip updating `last_updated`. It will make the mtimes of the new files a lie but should solve the problem.

Also, since the events are already in memory, we should think about making a way to extract the information needed for the index directly so we don't have to write to disk then read them in again. This shouldn't be too hard but may require some small refactoring of the update_index machinery.  It would be good to see something like this supported for both `EventBank` and `WaveBank` in order to maintain as much parity as possible between them.

**Comment by calum-chamberlain** [comment]
Agree on all points @sboltz and @d-chambers - how about I give this some more thought regarding update times and ensure that there is still an option to not update at all.  I will do some thinking and propose something more thorough.  Happy to open a different PR once I have something better if you want to close this one.

**Comment by calum-chamberlain** [comment]
I'm probably not going to be able to come back to this until the New Year, sorry all!  Happy to have this be closed if you want - it definitely requires more thought for locking access.

**Comment by d-chambers** [comment]
Sure no problem.

**Pull request closed without merging**
