### PR TITLE
joss submission

### PR DESCRIPTION
**Pull request by d-chambers**
This PR add the [JOSS](https://joss.theoj.org/) files required for submission. Using the [paper-previewing tool](https://whedon.theoj.org/) the paper renders like this:

[obsplus_joss_prelim.pdf](https://github.com/niosh-mining/obsplus/files/4284393/obsplus_joss_prelim.pdf)

I changed a few small things since it was last edited. @sboltz  and @calum-chamberlain can you take a look and approve this PR (or suggest changes) when you are satisfied?

### CODE REVIEW

**Comment by sboltz** [comment]
"Dataset versioning is also included through standard python package version"

What is meant by this?

Otherwise, I think it looks good.

**Comment by d-chambers** [comment]
> "Dataset versioning is also included through standard python package version"

This just means that each dataset is a python package, which has a version. That package version is also the dataset version.

Would it be more clear like this?

"Dataset versioning is accomplished through package versioning"

**Comment by sboltz** [comment]
> > "Dataset versioning is also included through standard python package version"
> 
> This just means that each dataset is a python package, which has a version. That package version is also the dataset version.
> 
> Would it be more clear like this?
> 
> "Dataset versioning is accomplished through package versioning"

That should work. I think there may have just been a word missing from the first one.

**Comment by d-chambers** [comment]
I ended up just deleting this bit because it should be obvious python packages have versions. 

As soon as ObsPy 1.2.1 is on conda-forge I will bump the requirements, do another ObsPlus release (0.1.0) and submit to joss. Thanks everyone!

**Pull request merged**
