### PR TITLE
Add option for naming based on split character

### PR DESCRIPTION
**Pull request by calum-chamberlain**
It is common for event resource ids to be similar to `smi:nz.org.geonet/2019p472707` - while this is useful to identify the agency, this can be annoying for writing filenames - `:` requires an escape character, and the extra path separation character results in extra nested directories.

This PR simply adds the option to format using the string after the `/`. This is a little selfish! If there is a better way (by allowing the user to specify their own formatter) then that would superseed this.

### CODE REVIEW

**Comment by d-chambers** [comment]
Sorry, can you give me a little more detail on this one? Only the last few (five) characters are used by default in the file name, at least if you want to use the obsplus generated one. Are there usually less than five characters from the end to the `/`, or do you want to use the event_id as the file name? Or maybe this is an issue with how the event_ids are stored in the SQLite index?

**Comment by calum-chamberlain** [comment]
I want to use, for example, just `2019p472707` from the above example. Or am I being ignorant and is the leading string before the `/` stripped already?

**Comment by d-chambers** [comment]
Oh I see. So you want to init a bank like so:

```python 
import obsplus 
ebank = obsplus.EventBank(name_structure="{year}{event_id_end}")
```
right?

Sorry yes, this should be fine. It seems like we could do some regexy custom formatter but I doubt there are too many more permutations of the event id people will need. :man_shrugging:  

I am in the field today but I should have time tomorrow to fix the issues with CI, then I will merge this in. Thanks!

**Comment by d-chambers** [comment]
Along these lines, 

It should be relatively easy to have a bank examine the files it contains and try to ascertain the `name_structure` and `path_structure` automatically but I haven't had the time to implement it yet.

**Comment by calum-chamberlain** [comment]
So I'm actually using it more like:
```python
import obsplus 
ebank = obsplus.EventBank(
    name_structure="{event_id_end}",
    path_structure="{year}/{month}/{event_id_end}"
)
```
To get an individual directory for each event, where `event_id_end` is just the part of the `event.resource_id` following a final `/`. I'm mostly trying to avoid nested directories named `smi:...`, and keeping "more-unique" event-ids - if I use just the last five characters of the resource_id then it looks like I could have some overlap in naming of events using the `{year}/{month}` directory structure - I could use `{year}/{month}/{day}` directories, but I haven't...

Sorry for slow reply, holiday last week!

**Pull request merged**
