### PR TITLE
Added an optional 'detailed' flag to get_uptime_df

### PR DESCRIPTION
**Pull request by shawnboltz**
This PR adds an optional 'detailed' argument to WaveBank's get_uptime_df method.

By default, this method just returns one row per NSLC that provides stats about the amount of data, number of gaps, length of gaps, etc. There's additionally the get_gaps_df method that returns a list of each gap in the data in the bank. This change fills a hole where I wanted a listing of each contiguous segment of data in the bank.

The default behavior of the method is not affected.

### CODE REVIEW

**Comment by shawnboltz** [comment]
Hey @d-chambers, there's no real rush to get this merged in as I can use my local changes in the meantime... but I noticed the CI is failing on something beyond my understanding of what it's doing. Do you mind taking a look when you have a chance?

**Comment by d-chambers** [comment]
Sure no problem. You just need this change. One of the repos used by pre-commit moved from gitlab to github:

image

**Comment by shawnboltz** [comment]
> Sure no problem. You just need this change. One of the repos used by pre-commit moved from gitlab to github:


Well that was easy... at some point I wouldn't mind a quick walkthrough of how the CI stuff is set up (or did you do a lecture on that that I missed?)

**Comment by shawnboltz** [comment]
Ok, @d-chambers ... Now flake8 is being really picky about things (and very considerately only informing me one line at a time), which screams of a version change, and with the change you had me make I see that we did downgrade it quite a bit? Is that really something we want to do? For its current complaint I honestly don't even see the problem, unless I'm doing something dumb and looking at the wrong file.

**Comment by d-chambers** [comment]
Hmmm... probably best to go with a more recent version. Feel free to change the version of any of the linting stuff. I don't remember why I downgraded (probably should just switch to current version). Probably best to run this locally, since the linter versions are pinned it should give you the same result for debugging. 

Happy to walk you through the CI stuff. I didn't have a lecture about it but would include that in an expanded version of the course.

**Comment by d-chambers** [comment]
> All right. I never have been able to figure out how to run the CI locally. But I will give it a try later when I’m on a computer with a bit more flexibilty.


I just meant the `pre-commit` bit. I am not sure how to run GH action locally either, though I hear it might be possible 🤷🏻 

You can run the pre-commit stuff like this:
```bash
pre-commit run --all
```

**Comment by d-chambers** [comment]
Ok, let's see if that fixes it. I will take a closer look tomorrow, but I think everything looks fine so far.

**Comment by shawnboltz** [comment]
Well, that would explain why I’ve never been able to do it. ;P

It looks like your change worked on my machine. No rush on looking at it more closely. It would probably make more sense to wait and merge it after you finish your other PR? Maybe it doesn’t matter that much.

**Comment by d-chambers** [comment]
> It would probably make more sense to wait and merge it after you finish your other PR? Maybe it doesn’t matter that much.

There might be some merge conflicts, so probably better to merge this first.

**Comment by d-chambers** [comment]
Hey @shawnboltz ,

Looking over this, my inclination is that perhaps the new functionality should just be a separate wavebank method? They are two different semantic outputs (a single line per channel vs lines for each contiguous segment). If I have understood correctly, when the `detailed` option is used, the output dataframe has nothing to do with "uptimes" but rather lists every contiguous data segment right? Isn't it very similar to `read_index` but just combines contiguous segments, or perhaps we think of it as the inverse of `get_gaps`? 

Also, do you anticipate a need to specify a maximum gap size? I could imagine in some cases you might want to find all segments with gaps smaller than X for some types of processing.

**Comment by sboltz** [comment]
@d-chambers, yeah, a new method would make sense. Really, the only reason I did it the way I did was I couldn't for the life of me figure out what to call it since get_availability and get_uptime were already taken. You're right that it is just the inverse of get_gaps. In fact it was struggling to bend the get_gaps output to my wishes that made me add this (because I never wanted to write it again).

I'm not quite sure I understand the max_gap argument? Are you meaning to combine segments w/ a gap smaller than x? That's what the min_gap argument should already do.

**Comment by d-chambers** [comment]
> I'm not quite sure I understand the max_gap argument? Are you meaning to combine segments w/ a gap smaller than x? That's what the min_gap argument should already do.

No, you're right, that is already there, I just overlooked it.

As far as a name, maybe `get_segments`, `get_blocks`, or `get_records`?

**Review by d-chambers — APPROVED** [review]
Looks good to me!

**Pull request merged**
