### PR TITLE
Udpate index subpaths

### PR DESCRIPTION
**Pull request by d-chambers**
This PR adds a `sub_paths` argument to both `EventBank.update_index` and `WaveBank.update_index`. It can be useful to avoid iterating all the files in a large bank when new files are added predictably (ie based on time).

What do you think about this @sboltz ?

### CODE REVIEW

**Comment by sboltz** [comment]
I think this seems reasonable. Does this address @calum-chamberlain 's issue as well?

**Comment by calum-chamberlain** [comment]
It may well do.  Keen to have a quick test,  but computer is unavailable for the next couple of days.

CJ Chamberlain, out of office

________________________________

**Comment by d-chambers** [comment]
Right, this should solve the main issue raised in #122. 

The main thing I am struggling with is how to keep the index valid (also discussed in #122). For summary, there are two potential problems:

a) files specified by the `sub_paths` parameter can get indexed multiple times. This will result in a bloated, slightly slower index depending on the level of duplication.

b) files added to the bank which are not included in the `sub_paths` parameter do not get indexed. 


I currently see three options:

1. Don't update the `last_updated` timestamp in bank database if the `sub_paths` argument is used when calling `update_index`.  This solves issue B but does not solve issue A.

2. Update the `last_updated` timestamp in the bank database when calling `update_index` using the `sub_paths` parameter. This solves issue A but does not solve issue B. It will be completely on the user to make sure all added files are accounted for.

3. Manually set the modified time of each file included in `sub_paths` back to a few minutes before the `last_updated` time. This solves both issues but feels a bit dirty to make the modified time of the files a lie. Maybe no one will care though, not sure.

I am leaning either towards 2 or 3 currently. Any strong feelings?

**Comment by sboltz** [comment]
I think I would be inclined towards Option 2. It’s a little risky (is there any possibility of adding files that get missed later, or would the user just have to ‘touch’ the files to get the bank to pick up the fact that they changed?) but Option 3 kinda makes me cringe.

**Comment by d-chambers** [comment]
Ok, I agree with you @sboltz, option 2 it is. 

I did two other things in this PR:

1. Removed the print statement that fired every time an index was updated.
2. For `put_waveforms` and `put_events` if `update_index` is `True` only the newly added files will be indexed, as discussed in #122. However, for code simplicity, I decided it is better to simply pass the paths of the new files to the indexer function rather than extract object information for the index directly. This results in some extra IO but lower code complexity.

Any other issues?

**Comment by d-chambers** [comment]
Ok, I am going to merge this as it is well tested and I don't think there are any remaining issues with it.

**Pull request merged**
