### PR TITLE
np.int Deprecation

### PR DESCRIPTION
**Pull request by sboltz**
This PR addresses the pending deprecation of `numpy.int`. Changes should be backwards compatible, though IDEs that support type hints might flag the use of `numpy.int` as an unexpected type.

### CODE REVIEW

**Comment by d-chambers** [comment]
This looks good and should have very little effect on existing codes.

One question though, what is this warnings_output.txt that is getting a bunch of additions in the source control? It looks like something we should be ignoring. Also, why so many more additions with this change?

**Comment by sboltz** [comment]
> One question though, what is this warnings_output.txt that is getting a bunch of additions in the source control? It looks like something we should be ignoring. Also, why so many more additions with this change?

Oh shoot. I didn't actually mean to commit that. The tests for obsplus currently spit out 4000+ warnings, so I had dumped them into a file to search for the issue I was trying to correct. Thoughts on the best way to walk that back?

**Comment by d-chambers** [comment]
Just remove it then push a new commit. When we merge we squash all the commits into one so there will be no record of it once it lands in master.

Now another thing (for another PR) is to address the warnings... I had it down to zero when we first released obsplus, any idea where they are coming from? There are probably just a few very noisy sources of warnings.

**Comment by sboltz** [comment]
Sounds good. It looks like the majority of them are deprecation warnings about `np.object` within the tables module and another about ipykernel. Not sure there's anything we can do about that right now except just wait for them to fix their code, unless we want to explicitly silence them.

I did notice another one that I can fix in this PR regarding `np.float`, though, so I'll go ahead and take care of that.

**Pull request merged**
