### PR TITLE
Cope with queries across the dateline

### PR DESCRIPTION
**Pull request by calum-chamberlain**
Event searches across the dateline with arguments like:
```
catalog.get_events(minlongitude=170, maxlongitude=181, ...)
```
did not return events across the dateline. This PR attempts to fix this!

To Do:
- [x] Write a test
- [x] Add a note to changelog.

### CODE REVIEW

**Comment by d-chambers** [comment]
Wow, what an edge case!

**Comment by d-chambers** [comment]
Hey @calum-chamberlain,

Did you need any help with this PR or is it just further down on your queue at the moment?

**Comment by calum-chamberlain** [comment]
Ah, sorry,  it slipped off the queue.  I'm in the field at the moment.  Maybe ping me next week if I haven't done anything useful.

CJ Chamberlain, out of office

________________________________

**Comment by d-chambers** [comment]
No worries, I just wanted to make sure you weren't waiting on me to do something.

**Comment by calum-chamberlain** [comment]
Currently there is a deliberate fail when setting a Longitude to 182 - this raises a `DataFrameContentError` because `obsplu.utils.geodetics` check for longitudes within +/- 180. I like this, but I'm concerned that it might result in errors when people don't expect them: I think I have seen longitudes > 180 in catalogs in the wild, but I don't have an example to hand. QuakeML nor ObsPy enforce longitudes +/- 180 either.

Do you want me to add a change to convert longitudes > 180 to `360 - longitude`, or keep it as is and just change my silly test? I don't mind either way.

I also may have made a mistake in my commit - the lint fails were unexpected.

**Comment by calum-chamberlain** [comment]
Oh, and I left print statements in that need to come out.

**Comment by d-chambers** [comment]
Sorry for the slow response.

Hmmm... good questions. Here is what I am thinking:

1. We allow lat/lons to be outside the specified ranges then we just map them to the appropriate domains in obsplus. This would affect queries on banks, as well as dataframe values, etc. I think we would want to use -180 to +180 for longitude and -90 to +90 for latitude but I am open to other conventions. 

2. We start trusting user input when maxlongitude < maxlongitude to mean query across the dateline. We would then have to detect this case and convert queries from the form 

`minlongitude` <  `longitude` < `maxlongitude`

to 

( -180 < `longitude' <  `maxlongitude`) | ('minlongitude` < `longitude` < 180)

This logic would need to be implemented in a helper function and used in several places that query dataframes, as well as the banks' query languages (HDF5 and SQLite) so it would be a rather major refactor. However, I think it would be the cleanest way to handle this properly. What do you think?

I am also curious to hear @sboltz 's opinion.

**Comment by sboltz** [comment]
This is definitely an interesting edge case that I wouldn't have considered. 

Part of me wants to remap them back to -180 - +180, just because I can see those longitudes breaking downstream processing that assumes longitudes in that range (it's akin to hypoinverse sometimes using 60.00 seconds for an origin time and breaking every implementation of a datetieme object I've ever seen). That being said, could there be a good reason for wanting to keep them greater than 180? It makes math easier, does it not? The more I think about it, actually, the more I'm inclined to just allow longitudes outside of that range. We definitely want to make sure that if we query with longitudes between, say 170-182 that it would still grab events between -180 and -178, though...

Also, this will only be a problem for longitude, no? There is no logical reason to try and query a latitude of 91?

**Comment by calum-chamberlain** [comment]
If we want to make the math simple we could just take the cosine of longitude to get a continuous +/-1 value - it would slow things down a bit though (`np.cos` for an array of 10,000 values took 213 µs vs 165 µs for `% 360`, so not really that much slower).

Also, yes, it should only be a problem for longitudes, and only if users (e.g. me) are doing silly things.

**Pull request closed without merging**
