### PR TITLE
SpatialCalculator DataFrame input columns

### PR DESCRIPTION
**Pull request by sboltz**
This PR addresses a subtle issue where if an input DataFrame was missing expected columns (or, in my case, they were named something other than what was expected) it would get passed down to the next parser in the chain, which was the `events_to_df` extractor. As a result the `events_to_df` extractor would simply return the dataframe with the "missing" columns added and filled with NaNs. This would later raise upon validating the df, but the error was much more obscure than if it were just caught earlier.

The fix to this was a little bit more involved than I expected because it also had to account for the fact that an events DataFrame is most likely going to have the column "depth" rather than "elevation". As a result, I am open to suggestions on cleaning it up a bit.

### CODE REVIEW

**Comment by d-chambers** [comment]
Hey @sboltz 

I think [this](https://niosh-mining.github.io/obsplus/versions/latest/notebooks/contributing.html#5.-Setup-precommit-hooks) may solve a lot of your linter problems.

**Comment by sboltz** [comment]
> Hey @sboltz
> 
> I think [this](https://niosh-mining.github.io/obsplus/versions/latest/notebooks/contributing.html#5.-Setup-precommit-hooks) may solve a lot of your linter problems.

Thanks. I have it set up to do that in my normal conda environment, I just haven't done it within the one that I used to make these changes. Hopefully the code should pass now.

**Comment by d-chambers** [comment]
Are [these lines](https://github.com/niosh-mining/obsplus/blob/7efe978ecb364f3a70db6b8da8f3408d2b130118/obsplus/utils/geodetics.py#L153-L155) unreachable now?

**Comment by sboltz** [comment]
> Are [these lines](https://github.com/niosh-mining/obsplus/blob/7efe978ecb364f3a70db6b8da8f3408d2b130118/obsplus/utils/geodetics.py#L153-L155) unreachable now?

No, they should still be very much reachable.

**Comment by sboltz** [comment]
> > Are [these lines](https://github.com/niosh-mining/obsplus/blob/7efe978ecb364f3a70db6b8da8f3408d2b130118/obsplus/utils/geodetics.py#L153-L155) unreachable now?
> 
> No, they should still be very much reachable.

Ah. I sort of see what's happening

**Comment by d-chambers** [comment]
Cool, looks good to me.

**Pull request merged**
