### PR TITLE
None bug

### PR DESCRIPTION
**Pull request by sboltz**
This pull request does two things:
1. It fixes a small bug in `obsplus.DataFrameExtractor` where if an object has a string attribute that is set to `None`, it was getting converted to `'None'`, rather than to an empty string (see #99) .
2. It modifies a couple of the events in the Crandall dataset that had `EventDescription`s with text='None'

One issue with this that I haven't entirely figured out yet is that it currently requires redownloading the Crandall dataset for the `EventDescription` change to take effect. I might recommend some kind of version numbering scheme on the datasets.

### CODE REVIEW

**Comment by sboltz** [comment]
Modified the `DataSet` abc to add a mechanism for versioning datasets. It works by raising an Exception if the version number associated with the downloaded data is less than the version on the `DataSet` child, or if the downloaded data does not have a version number associated with it. Deleting the events, stations, and waveforms directories associated with the dataset, in addition to the file containing the version number, will re-trigger the process of downloading the data.

Hopefully this will mitigate some of the problems that get introduced by modifying datasets.

**Comment by d-chambers** [comment]
Alright @sboltz,
Take a look at some of the minor changes I made and make sure I didn't ruin anything you were trying to do. If you are cool with it *squash and merge* it into master.

**Comment by d-chambers** [comment]
@sboltz,
Actually, giving this a bit more thought can we change one behavior? If the `Dataset` fails to load the version string from disk perhaps it should *create* one rather than raise? As it is now it will probably cause a big headache for the [opsdata template](https://github.com/seismopy/opsdata) in the case all the data is simply included, such as the [coal_node dataset](https://github.com/seismopy/opsdata_coal_node). 

Also, I realized it was writing the version file every time a dataset was instantiated. We probably don't want that so I moved it to only create the version file *after* some downloading has occurred.

**Comment by sboltz** [comment]
> @sboltz,
> Actually, giving this a bit more thought can we change one behavior? If the `Dataset` fails to load the version string from disk perhaps it should _create_ one rather than raise? As it is now it will probably cause a big headache for the [opsdata template](https://github.com/seismopy/opsdata) in the case all the data is simply included, such as the [coal_node dataset](https://github.com/seismopy/opsdata_coal_node).

So, there is actually an important reason for raising if it can't read it: namely that the existing datasets aren't going to have a version. This is the only way to force the re-download of the Crandall dataset. However, if you want to let that slide this time around then I suppose we could do that. But it is probably going to cause confusion for anyone with an existing install of obsplus.


> Also, I realized it was writing the version file every time a dataset was instantiated. We probably don't want that so I moved it to only create the version file _after_ some downloading has occurred.

Yes, that should definitely only happen after downloading.

**Comment by d-chambers** [comment]
Alternative proposal:
If the version str is not fetch-able from disk (by default from the simple version file) then it triggers the download logic automatically. This will force the updating of the `events` folder for the Crandal dataset, but also wont break the template datasets (which doesnt work with this branch currently).

Any downside to doing it this way?

**Comment by d-chambers** [comment]
I should add though, importantly it wont delete the old data under these circumstances. It will simply call the download methods and let them decide if they squash the old data or not. Because the download logic was called it will then check the hash of each data file, so if something still isn't right the user will be notified via that mechanism.

**Comment by sboltz** [comment]
I think that would be all right. I think the only potential downside would be if the user has changed the data on their end, but it sounds like the download methods should handle that (also, the user probably really shouldn't do that anyway)?

Would we then also want it to just call the download methods if the version is outdated, rather than the current behavior of raising?

**Comment by d-chambers** [comment]
> Would we then also want it to just call the download methods if the version is outdated, rather than the current behavior of raising?

I don't think so.

 A missing version file means something may be wrong, or it could just mean that the download methods have not yet been called. In the case of small datasets it is possible that all the data ship with the package, so no download methods need to be called. I don't think it would be common to detect a real problem via the mechanism.

On the other hand, a version conflict is confirmation that something is wrong. Since the download methods aren't guaranteed to re-download the data it is probably best to still raise. This would happen every time the dataset changes, which I suspect will be much more likely to identify real problems.

Thoughts?

**Comment by sboltz** [comment]
> A missing version file means something may be wrong, or it could just mean that the download methods have not yet been called. In the case of small datasets it is possible that all the data ship with the package, so no download methods need to be called. I don't think it would be common to detect a real problem via the mechanism.
>
> On the other hand, a version conflict is confirmation that something is wrong. Since the download methods aren't guaranteed to re-download the data it is probably best to still raise. This would happen every time the dataset changes, which I suspect will be much more likely to identify real problems.
> 
> Thoughts?

I think that makes sense. So, one question on datasets that have everything ship with them... if the version changes and this raises and tells the user to delete the files, are those `Dataset`s going to be able to redownload everything, or is the user going to have to intervene in some other way?

**Comment by sboltz** [comment]
Okay @d-chambers, I think this might be ready to go now. However, I did go ahead and update the hashes for the Crandall dataset and I'm a little bit weirded out by them (I re-downloaded the dataset first just to be safe to make sure there were no artifacts from me mucking around with things). It looks like most of the waveform file hashes are the same, which I would expect, but all of the event file hashes are different, despite not changing all of the events, and the stations are also different.

I understand that things are a little funny with the hashes because the data from IRIS can change, but does this make sense?

**Comment by d-chambers** [comment]
> So, one question on datasets that have everything ship with them... if the version changes and this raises and tells the user to delete the files, are those Datasets going to be able to re-download everything, or is the user going to have to intervene in some other way?

Good point. Currently the only such dataset is the [coal node dataset](https://github.com/seismopy/opsdata_coal_node) which is installed via PyPI, so when there is a new version the old one will be uninstalled by the pip machinery anyhow, so the versioning is already handled in that case. However, it would be best to make it possible to do something like this without pypi.

This would be a different PR, but what would you think about installing all of the datasets in a different location, maybe somewhere in the user's home directory by default but it could be changed via environmental variable. If you have a large dataset you may not want to be forced to install it in python's site packages anyhow. Let's think a bit more about the best way to handle this. I don't think we have many people using this yet so it shouldn't be too hard to change.

> does this make sense

I dont know why the other event files would have have changed, but keep in mind that the hashes are dependent on every single bit, so if any little thing changes about how obspy writes the file it will create a different hash. I wonder if there is some non-deterministic aspects in obspy's writing of quakeml and stationxml files? There may have been some small changes to the stationxmls on the IRIS end. Can you do a diff to see what has changed?

**Pull request merged**
